#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from thelethe/architectures/titans/models/origin/modular_origin.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_origin.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
from typing import Literal, Callable

from ...configuration_utils import (
    PretrainedTitansConfig,
    TitansVariants,
    layer_type_validation,
)
from ...modeling_rope_utils import rope_config_validation


class OriginConfig(PretrainedTitansConfig):
    r"""
    This is the configuration class to store the configuration of a [`OriginModel`]. It is used to instantiate a Titans
    model according to the specified arguments, defining the model architecture. Instantiating a configuration with the
    defaults will yield a similar configuration to that of the Titans 1.5B.

    Configuration objects inherit from [`PretrainedTitansConfig`] and can be used to control the model outputs. Read the
    documentation from [`PretrainedConfig`] for more information.

    Args:
        vocab_size (`int`, *optional*, defaults to 151936):
            Vocabulary size of the LLaMA model. Defines the number of different tokens that can be represented by the
            `inputs_ids` passed when calling [`LlamaModel`]
        hidden_size (`int`, *optional*, defaults to 2048):
            Dimension of the hidden representations.
        intermediate_size (`int`, *optional*, defaults to 5504):
            Dimension of the MLP representations.
        num_hidden_layers (`int`, *optional*, defaults to 24):
            Number of hidden layers in the Transformer decoder.
        num_attention_heads (`int`, *optional*, defaults to 32):
            Number of attention heads for each attention layer in the Transformer decoder.
        hidden_act (`str` or `function`, *optional*, defaults to `"silu"`):
            The non-linear activation function (function or string) in the decoder.
        max_position_embeddings (`int`, *optional*, defaults to 4096):
            The maximum sequence length that this model might ever be used with. Llama 1 supports up to 2048 tokens,
            Llama 2 up to 4096, CodeLlama up to 16384.
        initializer_range (`float`, *optional*, defaults to 0.02):
            The standard deviation of the truncated_normal_initializer for initializing all weight matrices.
        rms_norm_eps (`float`, *optional*, defaults to 1e-06):
            The epsilon used by the rms normalization layers.
        mini_batch_eps (`float`, *optional*, defaults to 1e-6):
            The epsilon used by the mini batch normalization layers.
        use_cache (`bool`, *optional*, defaults to `True`):
            Whether or not the model should return the last key/values attentions (not used by all models). Only
            relevant if `config.is_decoder=True`.
        variant (`Union[TitansVariants, Literal["lmm", "mac", "mae", "mag", "mal"]]`, *optional*, defaults to `TitansVariants.LMM`):
            The Titans memory type variant of the model to use.
        memory_depth (`int`, *optional*, defaults to 4):
            The memory depth of the Titans model.
        fixed_memory_size (`int`, *optional*, defaults to None):
            The fixed memory size of the Titans model. If None, the fixed memory size is set to same amount as memory depth.
            To disable fixed memory, set this to 0.
        pad_token_id (`int`, *optional*):
            Padding token id.
        bos_token_id (`int`, *optional*, defaults to 1):
            Beginning of stream token id.
        eos_token_id (`int`, *optional*, defaults to 2):
            End of stream token id.
        pretraining_tp (`int`, *optional*, defaults to 1):
            Experimental feature. Tensor parallelism rank used during pretraining. Please refer to [this
            document](https://huggingface.co/docs/transformers/main/perf_train_gpu_many#tensor-parallelism) to understand more about it. This value is
            necessary to ensure exact reproducibility of the pretraining results. Please refer to [this
            issue](https://github.com/pytorch/pytorch/issues/76232).
        tie_word_embeddings (`bool`, *optional*, defaults to `False`):
            Whether to tie weight embeddings
        rope_theta (`float`, *optional*, defaults to 10000.0):
            The base period of the RoPE embeddings.
        rope_scaling (`Dict`, *optional*):
            Dictionary containing the scaling configuration for the RoPE embeddings. NOTE: if you apply new rope type
            and you expect the model to work on longer `max_position_embeddings`, we recommend you to update this value
            accordingly.
            Expected contents:
                `rope_type` (`str`):
                    The sub-variant of RoPE to use. Can be one of ['default', 'linear', 'dynamic', 'yarn', 'longrope',
                    'llama3'], with 'default' being the original RoPE implementation.
                `factor` (`float`, *optional*):
                    Used with all rope types except 'default'. The scaling factor to apply to the RoPE embeddings. In
                    most scaling types, a `factor` of x will enable the model to handle sequences of length x *
                    original maximum pre-trained length.
                `original_max_position_embeddings` (`int`, *optional*):
                    Used with 'dynamic', 'longrope' and 'llama3'. The original max position embeddings used during
                    pretraining.
                `attention_factor` (`float`, *optional*):
                    Used with 'yarn' and 'longrope'. The scaling factor to be applied on the attention
                    computation. If unspecified, it defaults to value recommended by the implementation, using the
                    `factor` field to infer the suggested value.
                `beta_fast` (`float`, *optional*):
                    Only used with 'yarn'. Parameter to set the boundary for extrapolation (only) in the linear
                    ramp function. If unspecified, it defaults to 32.
                `beta_slow` (`float`, *optional*):
                    Only used with 'yarn'. Parameter to set the boundary for interpolation (only) in the linear
                    ramp function. If unspecified, it defaults to 1.
                `short_factor` (`list[float]`, *optional*):
                    Only used with 'longrope'. The scaling factor to be applied to short contexts (<
                    `original_max_position_embeddings`). Must be a list of numbers with the same length as the hidden
                    size divided by the number of attention heads divided by 2
                `long_factor` (`list[float]`, *optional*):
                    Only used with 'longrope'. The scaling factor to be applied to long contexts (<
                    `original_max_position_embeddings`). Must be a list of numbers with the same length as the hidden
                    size divided by the number of attention heads divided by 2
                `low_freq_factor` (`float`, *optional*):
                    Only used with 'llama3'. Scaling factor applied to low frequency components of the RoPE
                `high_freq_factor` (`float`, *optional*):
                    Only used with 'llama3'. Scaling factor applied to high frequency components of the RoPE
        adapt_base_lr (`float`, *optional*, defaults to 1.0): base learning rate for TTT learner
        chunk_size (`int`, *optional*, defaults to 16): chunk size (mini-batch size) for TTT learner
        scan_checkpoint_group_size (`int`, *optional*, defaults to 0):
            gradient checkpoint group size on seq dimension, 0 means no checkpointing.

    ```python
    >>> from thelethe.titans import OriginModel, OriginConfig

    >>> # Initializing a Titans-Origin 1.5B model config
    >>> configuration = OriginConfig()

    >>> # Initializing a Titans-Origin 1.5B model from config
    >>> model = OriginModel(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "titans_origin"

    def __init__(
        self,
        vocab_size: int = 151936,
        hidden_size: int = 2048,
        intermediate_size: int | tuple[int, int] = 5504,
        num_hidden_layers: int | tuple[int, int] = 6,
        num_attention_heads: int | tuple[int, int] = 32,
        hidden_act: str | Callable | tuple[str | Callable, str | Callable] = "silu",
        max_position_embeddings: int = 4096,
        initializer_range: float = 0.02,
        rms_norm_eps: float = 1e-6,
        mini_batch_eps: float = 1e-6,
        use_cache: bool = True,
        variant: TitansVariants
        | Literal["lmm", "mac", "mae", "mag", "mal"] = TitansVariants.LMM,
        memory_depth: int = 4,
        fixed_memory_size: int | None = None,
        pad_token_id: int | None = None,
        bos_token_id: int = 1,
        eos_token_id: int = 2,
        pretraining_tp: int = 1,
        tie_word_embeddings: bool = True,
        rope_theta: float = 10000.0,
        rope_scaling: dict | None = None,
        mlp_bias: bool = False,
        adapt_base_lr: float | tuple[float, ...] = 1.0,
        adapt_base_momentum: float | tuple[float, ...] = 0.9,
        adapt_base_weight_decay: float | tuple[float, ...] = 0.01,
        chunk_size: int = 128,
        scan_checkpoint_group_size: int = 0,
        attention_bias: bool = False,
        attention_dropout: float = 0.0,
        attention_layer_types: list | None = None,
        sliding_window: int | None = None,
        **kwargs,
    ):
        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads

        self.hidden_act = hidden_act
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.mini_batch_eps = mini_batch_eps
        self.pretraining_tp = pretraining_tp
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.rope_scaling = rope_scaling

        self.mlp_bias = mlp_bias
        self.adapt_base_lr = adapt_base_lr
        self.adapt_base_momentum = adapt_base_momentum
        self.adapt_base_weight_decay = adapt_base_weight_decay
        self.chunk_size = chunk_size
        self.fixed_memory_size = fixed_memory_size

        self.scan_checkpoint_group_size = scan_checkpoint_group_size

        self.attention_bias = attention_bias
        self.attention_dropout = attention_dropout
        if attention_layer_types is None:
            if sliding_window is None:
                attention_layer_types = ["full_attention"] * self.num_hidden_layers
            else:
                pattern = kwargs.get("sliding_window_pattern", 6)
                attention_layer_types = [
                    "sliding_attention" if bool((i + 1) % pattern) else "full_attention"
                    for i in range(self.num_hidden_layers)
                ]
        self.layer_types = attention_layer_types  # for Gemma3 compatibility
        self.attention_layer_types = attention_layer_types
        self.sliding_window = sliding_window

        rope_config_validation(self)
        layer_type_validation(self.layer_types)
        super().__init__(
            variant=variant,
            memory_depth=memory_depth,
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )


__all__ = ["OriginConfig"]
